version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo 'whoami' > ./test && bash ./test

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
